version: '3'

tasks:

  init-db:
    desc: Recreate and seed the database
    aliases: [init]
    cmds:
      - rm -f data/tasktree.db
      - task create-db
      - task seed-db

  create-db:
    desc: Create SQLite database from SQL schemas
    cmds:
      - mkdir -p data
      - cat src/sql/schemas/*.sql | sqlite3 data/tasktree.db
    generates:
      - data/tasktree.db

  seed-db:
    desc: Seed database with test data
    cmds:
      - sqlite3 data/tasktree.db < src/sql/seed.sql
