version: '3'

tasks:

  test:
    desc: Run all pytests
    silent: true
    cmds:
      - uv run pytest

  mcp:
    desc: Start the tasktree MCP Server
    silent: true
    cmds:
      - echo "Starting MCP server..."
      - uv run tasktree mcp

  init-db:
    desc: Recreate database (use SEED=true to seed with test data)
    silent: true
    aliases: [init]
    cmds:
      - echo "Recreating database..."
      - uv run tasktree init --force
      - echo "Complete!"

  create-db:
    desc: Create SQLite database from SQL schemas
    silent: true
    cmds:
      - echo "Creating SQLite database schemas..."
      - uv run tasktree init --force
    generates:
      - .tasktree/tasktree.db

  refresh-views:
    desc: Refresh all database views
    silent: true
    aliases: [rv]
    cmds:
      - echo "Refreshing database views..."
      - uv run tasktree refresh-views

  snapshot-export:
    desc: Export database to JSONL snapshot
    silent: true
    cmds:
      - echo "Exporting snapshot..."
      - |
          uv run python -c "from tasktree.core.paths import get_db_path, get_snapshot_path; from tasktree.io.snapshot import export_snapshot; export_snapshot(get_db_path(), get_snapshot_path())"
      - echo "Snapshot export complete."

  snapshot-import:
    desc: Import JSONL snapshot into database
    silent: true
    vars:
      OVERWRITE: '{{.OVERWRITE | default "true"}}'
    cmds:
      - echo "Importing snapshot..."
      - |
          uv run python -c "from tasktree.core.paths import get_db_path, get_snapshot_path; from tasktree.io.snapshot import import_snapshot; overwrite='{{.OVERWRITE}}'.lower()=='true'; import_snapshot(get_db_path(), get_snapshot_path(), overwrite=overwrite)"
      - echo "Snapshot import complete."

  graph-json:
    desc: Output the task dependency graph as JSON
    silent: true
    aliases: [json]
    cmds:
      - echo "Generating dependency graph JSON..."
      - sqlite3 .tasktree/tasktree.db "SELECT graph_json FROM v_graph_json" | jq .

  web-graph:
    desc: Launch graph server and open browser visualization
    silent: true
    aliases: [web]
    cmds:
      - echo "Starting graph server..."
      - |
        # Start the server in the background
        uv run tasktree start --port 8000 --db .tasktree/tasktree.db &
        SERVER_PID=$!
        
        # Wait for server to be ready
        sleep 2
        
        echo "Graph server running on http://localhost:8000"
        echo "Press Ctrl+C to stop the server"
        
        # Wait for the server process
        wait $SERVER_PID
