version: '3'

tasks:

  mcp:
    desc: Start the tasktree MCP Server
    cmds:
      - uv run src/mcp/server.py

  init-db:
    desc: Recreate database (use SEED=true to seed with test data)
    aliases: [init]
    vars:
      SEED: '{{.SEED | default "false"}}'
    cmds:
      - rm -f data/tasktree.db
      - task create-db
      - '{{if eq .SEED "true"}}task seed-db{{end}}'
      - task refresh-views

  create-db:
    desc: Create SQLite database from SQL schemas
    cmds:
      - mkdir -p data
      - cat sql/schemas/*.sql | sqlite3 data/tasktree.db
    generates:
      - data/tasktree.db

  seed-db:
    desc: Seed database with test data
    cmds:
      - sqlite3 data/tasktree.db < sql/seed.sql

  refresh-views:
    desc: Refresh all database views
    aliases: [rv]
    cmds:
      - cat sql/views/*.sql | sqlite3 data/tasktree.db

  graph-json:
    desc: Output the task dependency graph as JSON
    aliases: [json]
    cmds:
      - sqlite3 data/tasktree.db "SELECT graph_json FROM v_graph_json" | jq .

  draw:
    desc: Draw the task dependency graph in the terminal with colored highlighting
    cmds:
      - ./scripts/draw-graph.sh data/tasktree.db
