version: '3'

tasks:

  mcp:
    desc: Start the tasktree MCP Server
    cmds:
      - echo "Starting MCP server..."
      - uv run server.py
    silent: true

  init-db:
    desc: Recreate database (use SEED=true to seed with test data)
    aliases: [init]
    vars:
      SEED: '{{.SEED | default "false"}}'
    cmds:
      - echo "Recreating database..."
      - rm -f .tasktree/tasktree.db
      - task create-db
      - '{{if eq .SEED "true"}}task seed-db{{end}}'
      - task refresh-views
      - echo "Complete!"
    silent: true

  create-db:
    desc: Create SQLite database from SQL schemas
    cmds:
      - echo "Creating SQLite database schemas..."
      - mkdir -p data
      - cat src/tasktree_mcp/sql/schemas/*.sql | sqlite3 .tasktree/tasktree.db
    generates:
      - data/tasktree.db
    silent: true

  seed-db:
    desc: Seed database with test data
    cmds:
      - echo "Seeding database..."
      - sqlite3 .tasktree/tasktree.db < sql/seed.sql
    silent: true

  refresh-views:
    desc: Refresh all database views
    aliases: [rv]
    cmds:
      - echo "Refreshing database views..."
      - cat src/tasktree_mcp/sql/views/*.sql | sqlite3 .tasktree/tasktree.db
    silent: true

  graph-json:
    desc: Output the task dependency graph as JSON
    aliases: [json]
    cmds:
      - echo "Generating dependency graph JSON..."
      - sqlite3 .tasktree/tasktree.db "SELECT graph_json FROM v_graph_json" | jq .
    silent: true

  draw:
    desc: Draw the task dependency graph in the terminal with colored highlighting
    cmds:
      - echo "Drawing dependency graph..."
      - ./scripts/draw-graph.sh .tasktree/tasktree.db
    silent: true

  web-graph:
    desc: Launch graph server and open browser visualization
    aliases: [web]
    cmds:
      - echo "Starting graph server and opening browser..."
      - |
        # Start the server in the background
        uv run python scripts/graph-server.py --port 8000 --db .tasktree/tasktree.db &
        SERVER_PID=$!
        
        # Wait for server to be ready
        sleep 2
        
        # Open the HTML viewer in default browser
        if command -v xdg-open > /dev/null; then
          xdg-open "http://localhost:8000/"
        elif command -v open > /dev/null; then
          open "http://localhost:8000/"
        elif command -v start > /dev/null; then
          start "http://localhost:8000/"
        else
          echo "Could not detect browser opener. Please open http://localhost:8000/ manually."
        fi
        
        echo "Graph server running on http://localhost:8000"
        echo "Browser should open automatically. If not, open http://localhost:8000/"
        echo "Static viewer (no task panel): scripts/graph-viewer.html"
        echo "Press Ctrl+C to stop the server"
        
        # Wait for the server process
        wait $SERVER_PID
    silent: false
