version: '3'

tasks:

  mcp:
    desc: Start the tasktree MCP Server
    cmds:
      - cd src/mcp && uv run server.py

  init-db:
    desc: Recreate and seed the database
    aliases: [init]
    cmds:
      - rm -f data/tasktree.db
      - task create-db
      - task seed-db
      - task refresh-views

  create-db:
    desc: Create SQLite database from SQL schemas
    cmds:
      - mkdir -p data
      - cat src/sql/schemas/*.sql | sqlite3 data/tasktree.db
    generates:
      - data/tasktree.db

  seed-db:
    desc: Seed database with test data
    cmds:
      - sqlite3 data/tasktree.db < src/sql/seed.sql

  refresh-views:
    desc: Refresh all database views
    aliases: [rv]
    cmds:
      - cat src/sql/views/*.sql | sqlite3 data/tasktree.db

  graph-json:
    desc: Output the task dependency graph as JSON
    aliases: [json]
    cmds:
      - sqlite3 data/tasktree.db "SELECT graph_json FROM v_graph_json" | jq .

  draw:
    desc: Draw the task dependency graph in the terminal with colored highlighting
    cmds:
      - ./scripts/draw-graph.sh data/tasktree.db
